id: P474D1955
initial_creation_type: input
source_metadata:
  title: Chokgyur Dechen Lingpa
  language: fr
  description: 'The following texts are available as part of our series honouring
    the life and work of the famous tertön Chokgyur Dechen Lingpa (mchog gyur bde
    chen gling pa, 1829–1870):'
  volume:
    a6b33bac6fb24e0393e2f329989a4525:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    35c799b2e83946da909a2c76c333ea70:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    c7f94d77883a457281e67e3c2bbe3925:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    f1dc86f708a84c9b95abbe935e9b2654:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    b4160182914d423b92a9306e4c83ccb5:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    6ea8aeeb6c63465daa35655798b2c1a3:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    135764d48f2d4b62a5e44c982e1c5888:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    b4f294b60d294cff9373ef7f7719a09d:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    8816a52343fb486a8cdd8957cddb87e3:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Confession
    ac43cb3907b94fc58ef68a6dbe46699e:
      title: The Lament of Rudra
      parent: Confession
    281024eaed314cdcbc4d93d62c24676f:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Guru Rinpoche Prayers
    6c7d8517839345ef82e4314f2d887f20:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Guru Rinpoche Prayers
    1ab923631f8e4fc588ba965cdce8dae5:
      title: The Prayer in Six Vajra Lines
      parent: Guru Rinpoche Prayers
    c9de83ae171e45798b034fc13b991a64:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Guru Rinpoche Prayers
    23641dc6732d43bb87a02bfc837040f5:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Guru Rinpoche Prayers
    4e829867347a44a0814e32f39367dc6e:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Guru Rinpoche Prayers
    8e662d3efa224009a83cf6118b409178:
      title: A Concise Guru Yoga
      parent: Guru Yoga
    8ea40c54c6bd4c09969f2fbf2fa278b4:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: Long Life Prayers
    52a23557ef4e41edada4135d7e0a98cf:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Offering
    5f462fe99f8845b9bfbd10fa4e51c0b7:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Offering
    9c030e4e5fba4900aeba8c314ba54882:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Praise
    c58fcde37d6b4f5cbb38790335cbbefb:
      title: A Prayer to the Vidyādhara Gurus
      parent: Prayers
    d7f89d1386fc43fc8375607323ef4b37:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    bb1e09baeddf4be69901baa5ee68eede:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    fb1e1c874e5b45f586b457f08a285de7:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    390affd0887d4c509784699969644ad1:
      title: The Twenty-Eight Commitments
      parent: Tantra
    3ea46a0b5817416e9f05fa35d9c767ab:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T22:46:47.942753'
last_modified_at: '2022-02-28T22:46:47.942756'
